INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'África');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(1, "Andrés",  "Guzmán", "profesor@bolsadeideas.com","2018-01-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, "Linus",  "Torvalds", "linus@mail.com","2018-02-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, "Harry",  "Potter", "harry@potter.com","2018-03-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, "Cersei",  "Lannister", "cersei@lannister.com","2018-04-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, "Samsa",  "Stark", "samsa@stark.com","2018-05-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, "Ron",  "Wesley", "ron@wesley.com","2018-06-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, "Hermione",  "Granger", "hermione@granger.com","2018-07-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(5, "Tom",  "Riddle", "tom@riddle.com","2018-08-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(6, "Aria",  "Stark", "aria@stark.com","2018-09-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(7, "Remus",  "Lupin", "remus@lupin.com","2018-10-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(1, "Bellatrix",  "Lestrange", "bellatrix@lestrange.com","2018-11-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, "Raquel",  "Fernandez", "raquel@bolsadeideas.com","2018-12-01");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, "Lola",  "Castro", "lola@bolsadeideas.com","2018-12-31");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(6, "Serena",  "Abrams", "serena@bolsadeideas.com","2018-12-31");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(5, "Blair",  "Jackson", "blair@bolsadeideas.com","2018-12-31");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, "Penelope",  "Garcia", "penelope@bolsadeideas.com","2018-12-31");